(princ (characterp #\a))
(princ #\newline)
(princ (alpha-char-p #\a))
(princ #\newline)
(princ (char-upcase #\a))
(princ #\newline)
(princ (char-code #\a))
(princ #\newline)
(princ (code-char 98))
(princ #\newline)
(princ (char= #\a #\b))
(princ #\newline)
(princ (char< #\a #\b))
(princ #\newline)
(defun nextchar (c) "returns the next character from c" (code-char (+ (char-code c) 1)))
(princ (nextchar #\a))
(princ #\newline)


