(princ (car (cdr (cdr '(7 (* 5 4) (+ 3 1) (/ 4 1) 65)))))
(princ #\newline)
(princ (cdr '(7 (* 5 4) (+ 3 1) (/ 4 1) 65)))
(princ #\newline)
(princ (cdr (cdr '(7 (* 5 4) (+ 3 1) (/ 4 1) 65))))
(princ #\newline)
(princ (cdar '((a b) c d e)))
(princ #\newline)
(princ (cadr '((a b) c d e)))
